# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/skillet/git/ECE433/FinalProject/FinalProject.cache/wt [current_project]
set_property parent.project_path /home/skillet/git/ECE433/FinalProject/FinalProject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/skillet/git/ECE433/FinalProject/FinalProject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/imports/FinalProjectGivenFiles/CRTClock2021Template.v
  /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/imports/FinalProjectGivenFiles/CRTcontroller2021fall.v
  /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/imports/FinalProjectGivenFiles/FallingEdgePositiveOneShot.v
  /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/imports/FinalProjectGivenFiles/Game2021fall.v
  /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/imports/FinalProjectSoundGiven/InputModule.v
  /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/new/LineClockUnit.v
  /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/imports/FinalProjectSoundGiven/ThreeMusicNotes.v
  /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/imports/FinalProjectGivenFiles/UniversalCounter2021fall.v
  /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/imports/FinalProjectSoundGiven/WaveForm.v
  /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/imports/FinalProjectGivenFiles/hsyncModule2021fall.v
  /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/imports/FinalProjectGivenFiles/vsyncModule2021fallTemplate.v
  /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/imports/FinalProjectGivenFiles/PongGame2021fall_template.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/constrs_1/new/PongGame.xdc
set_property used_in_implementation false [get_files /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/constrs_1/new/PongGame.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top PongGame2021fall_template -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef PongGame2021fall_template.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file PongGame2021fall_template_utilization_synth.rpt -pb PongGame2021fall_template_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
