# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/ip/clkGen25/clkGen25.xci
# IP: The module: 'clkGen25' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/ip/clkGen25/clkGen25_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkGen25'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/ip/clkGen25/clkGen25.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkGen25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/ip/clkGen25/clkGen25_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkGen25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/ip/clkGen25/clkGen25.xci
# IP: The module: 'clkGen25' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/ip/clkGen25/clkGen25_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkGen25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/ip/clkGen25/clkGen25.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkGen25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/skillet/git/ECE433/FinalProject/FinalProject.srcs/sources_1/ip/clkGen25/clkGen25_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkGen25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
