#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Nov 30 10:24:39 EST 2021
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 3bcdb8cf97d0471587573487b38788c4 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot CRTcontroller2021fall_tb_behav xil_defaultlib.CRTcontroller2021fall_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 3bcdb8cf97d0471587573487b38788c4 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot CRTcontroller2021fall_tb_behav xil_defaultlib.CRTcontroller2021fall_tb xil_defaultlib.glbl -log elaborate.log

