@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Sep 21 22:38:36 -0400 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim hw2p6ece433fall2021detect11010_tb_behav -key {Behavioral:sim_1:Functional:hw2p6ece433fall2021detect11010_tb} -tclbatch hw2p6ece433fall2021detect11010_tb.tcl -view C:/Xilinx/projects/hw2p6/hw2p6ece433fall2021detect11010_tb_behav.wcfg -log simulate.log"
call xsim  hw2p6ece433fall2021detect11010_tb_behav -key {Behavioral:sim_1:Functional:hw2p6ece433fall2021detect11010_tb} -tclbatch hw2p6ece433fall2021detect11010_tb.tcl -view C:/Xilinx/projects/hw2p6/hw2p6ece433fall2021detect11010_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
