# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/skillet/git/ECE433/lab6/lab6.srcs/sources_1/ip/clk80Gen/clk80Gen.xci
# IP: The module: 'clk80Gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/skillet/git/ECE433/lab6/lab6.srcs/sources_1/ip/clk80Gen/clk80Gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk80Gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/skillet/git/ECE433/lab6/lab6.srcs/sources_1/ip/clk80Gen/clk80Gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk80Gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/skillet/git/ECE433/lab6/lab6.srcs/sources_1/ip/clk80Gen/clk80Gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk80Gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/skillet/git/ECE433/lab6/lab6.srcs/sources_1/ip/clk80Gen/clk80Gen.xci
# IP: The module: 'clk80Gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/skillet/git/ECE433/lab6/lab6.srcs/sources_1/ip/clk80Gen/clk80Gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk80Gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/skillet/git/ECE433/lab6/lab6.srcs/sources_1/ip/clk80Gen/clk80Gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk80Gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/skillet/git/ECE433/lab6/lab6.srcs/sources_1/ip/clk80Gen/clk80Gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk80Gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
