set_property SRC_FILE_INFO {cfile:C:/Xilinx/projects/lab1part1SCC/lab1part1SCC.srcs/constrs_1/new/lab1part1gate3SCC.xdc rfile:../../../lab1part1SCC.srcs/constrs_1/new/lab1part1gate3SCC.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports All]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports Blink]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J13 [get_ports Left]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports Right]
