#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Oct 07 02:58:56 EDT 2021
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto a93d617c9c044286bf9c6a1a0d49a6fa --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot MultiplierTB_behav xil_defaultlib.MultiplierTB xil_defaultlib.glbl -log elaborate.log"
xelab -wto a93d617c9c044286bf9c6a1a0d49a6fa --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot MultiplierTB_behav xil_defaultlib.MultiplierTB xil_defaultlib.glbl -log elaborate.log

