#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Nov 29 00:06:37 EST 2021
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto d00343d8cc3f4da88f8cc60325d7d657 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot TxModule_ToplevelTB_ece433fall2021_behav xil_defaultlib.TxModule_ToplevelTB_ece433fall2021 xil_defaultlib.glbl -log elaborate.log"
xelab -wto d00343d8cc3f4da88f8cc60325d7d657 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot TxModule_ToplevelTB_ece433fall2021_behav xil_defaultlib.TxModule_ToplevelTB_ece433fall2021 xil_defaultlib.glbl -log elaborate.log

