#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Nov 28 23:56:00 EST 2021
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim TxModule_ToplevelTB_ece433fall2021_behav -key {Behavioral:sim_1:Functional:TxModule_ToplevelTB_ece433fall2021} -tclbatch TxModule_ToplevelTB_ece433fall2021.tcl -log simulate.log"
xsim TxModule_ToplevelTB_ece433fall2021_behav -key {Behavioral:sim_1:Functional:TxModule_ToplevelTB_ece433fall2021} -tclbatch TxModule_ToplevelTB_ece433fall2021.tcl -log simulate.log

