set_property PACKAGE_PIN P17 [get_ports All]
set_property PACKAGE_PIN N17 [get_ports Blink]
set_property PACKAGE_PIN J13 [get_ports Left]
set_property PACKAGE_PIN H17 [get_ports Right]
set_property IOSTANDARD LVCMOS33 [get_ports All]
set_property IOSTANDARD LVCMOS33 [get_ports Blink]
set_property IOSTANDARD LVCMOS33 [get_ports Left]
set_property IOSTANDARD LVCMOS33 [get_ports Right]
